export const GET_LIST_COURSE = "GET_LIST_COURSE";
export const GET_DETAIL_COURSE = "GET_DETAIL_COURSE";
export const SET_TOKEN = "SET_TOKEN";
export const GET_CATEGORIES_COURSE = "GET_CATEGORIES_COURSE";
